name: Scraping Linio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run scraping script
      run: |
        python main.py --product "laptop"

    - name: Check if CSV file exists
      run: |
        if [ ! -f linio_scraped_data.csv ]; then
          echo "CSV file was not generated"
          exit 1
        fi

    - name: Upload CSV file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: linio-scraped-data
        path: linio_scraped_data.csv


