name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Configura el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Cambia según tu versión

    # Instala dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ejecuta pruebas
    - name: Run tests
      run: |
        pytest
